apiVersion: v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
        component: server
  template:
      metadata:
         labels:
            component: api
      spec:
          containers: 
              - name: simple_blog_api
                image: simidas/simple_blog_api
                ports:
                    - containerPort: 3000
                env:
                    - name: POSTGRES_HOST
                      value: postgres-cluster-ip-service
                    - name: POSTGRES_PORT
                      value: "5432" 
                    - name: POSTGRES_USERNAME
                      value: postgres
                    - name: POSTGRES_DB
                      value: simple_blog_api
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                          secretKeyRef:
                              key: POSTGRES_PASSWORD
                              name: pgpassword
                              valueFrom:
                                  secretKeyRef:
                                         key: POSTGRES_PASSWORD
                                         name: pgpassword
                resources: 
                       limits:
                           memory: "128Mi"
                           cpu: "500m"
                           
              
