apiVersion: v1
kind: Ingress
metadata:
    name: ingres-service
    annotations:
         kubernetes.io/ingres.class: nginx
         nginx.ingres.kubernetes.io/use-regex: "true"
         nginx.ingres.kubernetes.io/rewrite-target: /$1
spec:
    rules:
        - https:
               paths:
                    paths: /?(.*)
                    pathType: Prefix
                    backend:
                          service:
                               name: api-cluster-ip-service
                               port: 
                                   number: 3000
